name: sponge_client_dart
description: Sponge client for Dart. It simplifies connecting to a remote Sponge service.
homepage: https://github.com/softelnet/sponge_client_dart
version: 1.16.3

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  meta: ^1.1.8
  http: ^0.12.2
  synchronized: ^2.2.0
  quiver: ^2.1.3
  timezone: ^0.5.7
  intl: ^0.16.1
  equatable: ^1.2.3
  collection: ^1.14.12
  logging: ^0.11.4

dev_dependencies:
  test: ^1.15.3
  pedantic: ^1.9.0
